from database import SessionLocal
from models.practica import Practica

db = SessionLocal()

PRACTICAS = [
    # TOMOGRAFIA
    ("TAC DE CEREBRO", "TOMOGRAFIA"),
    ("TAC DE CEREBRO CON CONTRASTE", "TOMOGRAFIA"),
    ("TAC DE TORAX", "TOMOGRAFIA"),
    ("TAC DE TORAX CON CONTRASTE", "TOMOGRAFIA"),
    ("TAC COMPLETA DE ABDOMEN", "TOMOGRAFIA"),
    ("TAC COMPLETA DE ABDOMEN CON CONTRASTE", "TOMOGRAFIA"),
    ("TAC DE PELVIS", "TOMOGRAFIA"),
    ("TAC DE PELVIS CON CONTRASTE", "TOMOGRAFIA"),
    ("TAC DE OTROS ORGANOS Y REGIONES", "TOMOGRAFIA"),
    ("TAC DE CUELLO", "TOMOGRAFIA"),

    # RADIOGRAFIA
    ("RX DE TORAX", "RADIOGRAFIA"),
    ("RX DE COLUMNA CERVICAL", "RADIOGRAFIA"),
    ("RX DE COLUMNA DORSAL", "RADIOGRAFIA"),
    ("RX DE COLUMNA LUMBAR", "RADIOGRAFIA"),
    ("RX DE HOMBRO", "RADIOGRAFIA"),
    ("RX DE CODO", "RADIOGRAFIA"),
    ("RX DE MUÑECA", "RADIOGRAFIA"),
    ("RX DE MANO", "RADIOGRAFIA"),
    ("RX DE PELVIS", "RADIOGRAFIA"),
    ("RX DE CADERA", "RADIOGRAFIA"),
    ("RX DE RODILLA", "RADIOGRAFIA"),
    ("RX DE TOBILLO", "RADIOGRAFIA"),
    ("RX DE PIE", "RADIOGRAFIA"),
    ("RX DE CRANEO", "RADIOGRAFIA"),
    ("RX DE ABDOMEN SIMPLE", "RADIOGRAFIA"),
    ("RX DENTAL (PERIAPICAL / BITEWING)", "RADIOGRAFIA"),
    ("RX ORTOPANTOMOGRAFIA (PANORAMICA)", "RADIOGRAFIA"),

    # ECOGRAFIA
    ("ECOGRAFIA ABDOMINAL", "ECOGRAFIA"),
    ("ECOGRAFIA PELVICA (GINECOLOGICA)", "ECOGRAFIA"),
    ("ECOGRAFIA OBSTETRICA", "ECOGRAFIA"),
    ("ECOGRAFIA MAMARIA", "ECOGRAFIA"),
    ("ECOGRAFIA TIROIDEA", "ECOGRAFIA"),
    ("ECOGRAFIA RENAL", "ECOGRAFIA"),
    ("ECOGRAFIA VESICAL", "ECOGRAFIA"),
    ("ECOGRAFIA PROSTATICA (TRANSRECTAL)", "ECOGRAFIA"),
    ("ECOGRAFIA TESTICULAR", "ECOGRAFIA"),
    ("ECOGRAFIA MUSCULOESQUELETICA", "ECOGRAFIA"),
    ("ECOGRAFIA DOPPLER (VASCULAR)", "ECOGRAFIA"),
    ("ECOCARDIOGRAMA", "ECOGRAFIA"),
    ("ECOGRAFIA TRANSVAGINAL", "ECOGRAFIA"),

    # PET
    ("PET CON FDG", "PET"),
    ("PET CON COLINA", "PET"),
    ("PET CON PSMA", "PET"),

    # ELECTRO / MAPEO
    ("EEG", "ELECTRO_MAPEO"),
    ("MAPEO CEREBRAL", "ELECTRO_MAPEO"),

    # RADIOTERAPIA
    ("RT 3D", "RADIOTERAPIA"),
    ("IMRT", "RADIOTERAPIA"),

    # CAMARA GAMMA
    ("CENTELLOGRAMA OSEO", "CAMARA_GAMMA"),
    ("CENTELLOGRAMA RENAL", "CAMARA_GAMMA"),
    ("CENTELLOGRAMA DE TIROIDES", "CAMARA_GAMMA"),
    ("ESTUDIO DINAMICO RENAL", "CAMARA_GAMMA"),
    ("CURVA DE CAPTACION TIROIDEA", "CAMARA_GAMMA"),
    ("BARRIDO CORPORAL TOTAL", "CAMARA_GAMMA"),
]

for nombre, categoria in PRACTICAS:
    existente = db.query(Practica).filter(Practica.nombre == nombre).first()
    if not existente:
        db.add(Practica(nombre=nombre, categoria=categoria))

db.commit()
db.close()
print("✅ Prácticas cargadas / actualizadas correctamente")
